apiVersion: web.example.com/v1
kind: Website
metadata:
  labels:
    app.kubernetes.io/name: operator-example
    app.kubernetes.io/managed-by: kustomize
  name: website-sample
spec:
  # TODO(user): Add fields here
